### ISSUE TITLE
opening config.org in emacs --debug-init mode back trace

### ISSUE THREAD

**Issue by dagnachewa** [tecosaur/emacs-config#14]
Package cl is deprecated
Battery status not available
Battery status not available
Battery status not available
Battery status not available
Battery status not available
Battery status not available
Battery status not available
Battery status not available
Battery status not available
Battery status not available
Battery status not available
Battery status not available
md-roam is active
org-super-agenda-mode enabled.
org-super-agenda-mode enabled.
org-super-agenda-mode enabled.
org-super-agenda-mode enabled.
org-super-agenda-mode enabled.
org-super-agenda-mode enabled.
Doom loaded 0 packages across 110 modules in 3.595s
Symbol’s value as variable is void: vc-log-view-type

**Comment by dagnachewa** [comment]
I did this backtrace because I could not export my config.org to html, I get Symbol’s value as variable is void: vc-log-view-type

**Comment by tecosaur** [comment]
Yea with `vc-log-view-type`, that's an issue outside of my config that's caused by this line,

```org
#+date: {{{modification-time(%Y-%m-%d %H:%M, t)}}}
```

`modification-time` is an Org-defined macro that tries to use `vc-*` functions without making sure `vc` is loaded 🙁.

As for the `mixed-pitch-mode`, not sure what's going on there, it should be autoloaded by Doom…
