### ISSUE TITLE
Graphic not showing correctly

### ISSUE THREAD

**Issue by rodal2** [tecosaur/emacs-config#17]
I love your config, it is superbly curated!
In the html export of your config, the graphic comparing the different editors does not show properly.
I remember it was showing properly in the past and it is showing properly in the pdf version.

I find it to be very aesthetic, would you mind pointing me towards the tools you used to create it, or even share some of the code? 

Thank you for the inspiration!

**Comment by tecosaur** [comment]
> In the html export of your config, the graphic comparing the different editors does not show properly.

That's because Org is using an `<object>` for the SVG and it dosen't work too well. When it's changed to an `<img>` (which has been done in Org `HEAD`) it will go back to normal.

> I find it to be very aesthetic, would you mind pointing me towards the tools you used to create it, or even share some of the code?

You're looking at it :stuck_out_tongue: 
1. https://tecosaur.github.io/emacs-config/config.html#html-export
2. [misc/org-css](https://github.com/tecosaur/emacs-config/tree/master/misc/org-css)
