### ISSUE TITLE
Can't run second step of the installation.

### ISSUE THREAD

**Issue by JxJxxJxJ** [tecosaur/emacs-config#41]
After 

> emacs --batch --eval "(progn (require 'org) (setq org-confirm-babel-evaluate nil) (org-babel-tangle-file \"~/.config/doom/config.org\"))"

This happens : https://pastebin.com/R5xiMbe0

Previously, as I thought this only tangled the files so the *.el files could get generated, I did it manually. But maybe I should have started questioning why I could not run this in the first place. 

Trying to see if I have something bad in my end.

**Comment by tecosaur** [comment]
It's because the Emacs-bundled Org version is too old for what I'm doing during tangle. I would have thought the bootstrap would have triggered, but this may be related to what you did in #40.

I'd also like to take this opportunity to highlight an excerpt from https://tecosaur.github.io/emacs-config/config.html#notes-unwary-adventurer

![image](https://user-images.githubusercontent.com/20903656/204448403-d823756c-b7a9-4961-89a8-d522dcd9b326.png)

**Comment by JxJxxJxJ** [comment]
I see. Unfortunately copying chunks lead to more undersired effects since the bits are often times communicated with other bits of the config, often times one is leading with errors or weird functionalities still because of that. I'm trying to go through a different approach this time

**Comment by JxJxxJxJ** [comment]
As a suggestion, wouldn't a 'list of dependencies' or some sort be nice information to have? 

Oh and just in case, this was made just after cloning the repo with everything fresh. The snippet in #40 was still in config.org.
